version: '3.8'

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '48140:5432'
  customer_db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer_db
    ports:
      - '48141:5432'
  customer_mysql_db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: customer_db
    ports:
      - '48142:3306'
    volumes:
      - ./.docker/volumns/mysql:/var/lib/mysql
